version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: lbt-honeybee
    versions:
    - 0.3.26
    - 0.4.27
    - 0.4.28
    - 0.4.29
    - 0.4.30
    - 0.4.34
    - 0.4.37
    - 0.4.38
    - 0.4.74
    - 0.4.77
    - 0.4.90
    - 0.4.91
    - 0.4.95
  - dependency-name: setuptools
    versions:
    - 54.1.3
  - dependency-name: pydantic
    versions:
    - "1.8"
    - 1.8.1
  - dependency-name: honeybee-radiance
    versions:
    - 1.29.10
    - 1.29.11
    - 1.29.4
    - 1.29.6
    - 1.29.7
    - 1.29.8
    - 1.29.9
  - dependency-name: honeybee-core
    versions:
    - 1.42.2
    - 1.42.3
    - 1.42.4
    - 1.42.5
    - 1.42.6
    - 1.42.7
  - dependency-name: ladybug-geometry
    versions:
    - 1.23.2
    - 1.23.3
    - 1.23.4
  - dependency-name: coveralls
    versions:
    - 3.0.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
